do.debug:
	Rscript model/debug.r && echo [OK]
do.main:
	Rscript model/main.r && echo [OK]
do.fit:
	Rscript model/fit.r && echo [OK]
do.data.engage:
	Rscript data/engage.r && echo [OK]
do.data.kenya:
	Rscript data/kenya.r && echo [OK]
do.iso:
	Rscript model/do/iso/main.r && echo [OK]
do.thr:
	Rscript model/do/thr/main.r && echo [OK]
do.speed:
	Rscript model/do/speed/main.r && echo [OK]
do.tikz:
	cd tikz && make all && echo [OK]
