do.debug:
	Rscript .debug/debug.r && echo [OK]
do.main:
	Rscript model/main.r && echo [OK]
do.handfit:
	Rscript model/handfit.r && echo [OK]
do.vax-t0:
	Rscript model/scenario/vax-t0/main.r && echo [OK]
do.graph.test:
	Rscript graph/test.r && echo [OK]

